TARGETS  = bootencrypt
LIB      = 

FILE_TYPE= cpp

ROOT_DIR =..
LIB_TYPE =
SRC_DIR  =.

INC_DIRS =  $(ROOT_DIR)/include \
			$(ROOT_DIR)/include/common \

LIB_DIRS =  $(ROOT_DIR)	    
STATIC_LIBS = $(ROOT_DIR)/libs/libcommon \
	
DYNAMIC_LIBS= -lrt -ldl -lm  -lpthread
include ../.make.rule
