TARGETS  = 
LIB      = libcommon

FILE_TYPE= cpp

SRC_DIR  =.
ROOT_DIR =..
LIB_TYPE =static
#LIB_TYPE=

INC_DIRS =  $(ROOT_DIR)/include/common \

		

LIB_DIRS =  $(ROOT_DIR)	    
STATIC_LIBS =  
DYNAMIC_LIBS= -lrt -ldl -lm  -lpthread 
include ../.make.rule
